name: Force Update Server Files

on:
  workflow_dispatch:

jobs:
  force-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Force update server files
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "🔄 ПРИНУДИТЕЛЬНОЕ ОБНОВЛЕНИЕ СЕРВЕРА"
          echo "===================================="
          
          cd /var/www/bot_business_card
          
          # Показываем текущее состояние
          echo "📍 Текущий коммит:"
          git log -1 --oneline
          
          echo "📋 Git статус:"
          git status
          
          # ПРИНУДИТЕЛЬНО сбрасываем все изменения
          echo "🔄 Сбрасываем локальные изменения..."
          git stash
          git reset --hard HEAD
          git clean -fd
          
          # ПРИНУДИТЕЛЬНО получаем последние изменения
          echo "📥 Принудительно получаем изменения..."
          git fetch --all
          git reset --hard origin/main
          
          # Проверяем что получили
          echo "✅ Новый коммит:"
          git log -1 --oneline
          
          # Проверяем наш файл
          echo "🔍 Проверяем avito_messenger.html:"
          if grep -q "🚨 ОТЛАДКА" app/admin/templates/avito_messenger.html; then
            echo "✅ DEBUG БЛОК НАЙДЕН!"
            echo "✅ Размер файла: $(wc -c < app/admin/templates/avito_messenger.html) bytes"
          else
            echo "❌ ФАЙЛ ВСЁЩЕ НЕ ОБНОВЛЁН!"
            echo "📝 Первые 10 строк:"
            head -10 app/admin/templates/avito_messenger.html
          fi
          
          # Перезапускаем PM2 для применения изменений
          echo "🚀 Перезапускаем PM2..."
          pm2 restart bot-business-card
          
          # Ждем запуска
          sleep 5
          
          # Проверяем статус
          echo "📊 PM2 статус:"
          pm2 status
          
          echo "✅ ПРИНУДИТЕЛЬНОЕ ОБНОВЛЕНИЕ ЗАВЕРШЕНО!"